version: '3'

services:
  prometheus-cluster-demo:
    image: prometheus-cluster-demo:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - "8080:8080"

  prometheus1:
    image: prom/prometheus:latest
    depends_on:
      - prometheus-cluster-demo
    volumes:
      - ./config/prometheus1.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    ports:
      - "9090:9090"

  prometheus2:
    image: prom/prometheus:latest
    depends_on:
      - prometheus-cluster-demo
    volumes:
      - ./config/prometheus2.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    ports:
      - "9091:9090"