global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']
  - job_name: 'spring-actuator'
    static_configs:
      - targets: ['prometheus-cluster-demo:8080']
    metrics_path: '/actuator/prometheus'